name: Deploy API to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Render
        run: "curl -X POST -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}'' -d '{}' https://api.render.com/deploy"